// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl.menu'], ['zz.ui.mdl.menu.controllers.Menu', 'zz.ui.mdl.menu.enums.CSS', 'zz.ui.mdl.menu.tpl', 'zz.ui.mdl.menu.views.Menu'], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/menu.js', ['zz.ui.mdl.menu.controllers.Menu'], ['goog.array', 'goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component', 'goog.ui.Menu', 'zz.ui.mdl.controllers.BaseControl', 'zz.ui.mdl.menu.controllers.MenuItem', 'zz.ui.mdl.menu.enums.CSS', 'zz.ui.mdl.menu.services.Popup', 'zz.ui.mdl.menu.views.Menu'], false);
goog.addDependency('/../../../../../../../lib/sources/enums/const.js', ['zz.ui.mdl.menu.enums.CONST'], [], false);
goog.addDependency('/../../../../../../../lib/sources/enums/css.js', ['zz.ui.mdl.menu.enums.CSS'], [], false);
goog.addDependency('/../../../../../../../lib/sources/enums/keycodes.js', ['zz.ui.mdl.menu.enums.KEYCODES'], [], false);
goog.addDependency('/../../../../../../../lib/sources/services/popup.js', ['zz.ui.mdl.menu.services.Popup'], ['goog.events', 'goog.events.EventType', 'goog.object'], false);
goog.addDependency('/../../../../../../../lib/sources/views/menu.js', ['zz.ui.mdl.menu.views.Menu'], ['goog.array', 'goog.dom.classlist', 'goog.style', 'goog.ui.MenuRenderer', 'zz.ui.mdl.menu.enums.CONST', 'zz.ui.mdl.menu.enums.CSS', 'zz.ui.mdl.menuitem.enums.CSS'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.menuitem/lib/sources/base.js', ['zz.ui.mdl.menuitem'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/base.js', ['zz.ui.mdl'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/controllers/basecontrol.js', ['zz.ui.mdl.controllers.BaseControl'], ['goog.events.Event', 'goog.ui.Component', 'goog.ui.Control', 'zz.i18n.services.DefaultFormatter', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/views/baseview.js', ['zz.ui.mdl.views.BaseView'], ['goog.ui.ControlRenderer', 'goog.ui.registry'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/base.js', ['zz.i18n'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/decimalformatter.js', ['zz.i18n.services.DecimalFormatter'], ['goog.i18n.NumberFormat', 'goog.i18n.NumberFormat.Format'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/defaultformatter.js', ['zz.i18n.services.DefaultFormatter'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/soymessages.js', ['zz.i18n.services.SoyMessages'], ['goog.array', 'goog.dom', 'soy'], false);
